Fix 'distribute lastprivate(n)' (#10)
* Fix 'distribute lastprivate(n)'

OpenMP 5.2 has the following:
"Restrictions to the lastprivate clause are as follows:
"- A list item must not appear in a lastprivate clause on a work-distribution
   construct if the corresponding region binds to the region of a
   parallelism-generating construct in which the list item is private. [...]"

Prior OpenMP versions had a similar restrictions - but only considered the
parallel construct, missing to include other parallelism-generating constructs.
The new wording avoids listening all constructs (and missing to update the list)
by using the generic category names.  Note: 'distribute' has the property
'work-distribution' while 'teams' has the 'Properties: parallelism-generating,
thread-limiting, context-matching".

Solved by moving 'int n' before the parallelism-generating construct, which
adds an implicit 'shared(n)' clause to the teams construct.

Note: This also fix a long-standing issue with GCC, which rejected the
testcase with:
  error: lastprivate variable ‘n’ is private in outer context

* t-distribute-simd-clauses/test.c: Move 'int n' decl before 'omp teams'.
* t-unified-distribute-simd-clauses/test.c: Likewise.

* t-*distribute-simd-clauses: Fix teams restriction

Move 'int n' before 'omp target' for 'omp teams' as:
"If a teams region is nested inside a target region, the corresponding
target construct must not contain any statements, declarations or
directives outside of the corresponding teams construct."

* t-distribute-simd-clauses/test.c
* t-unified-distribute-simd-clauses/test.c

* t-*distribute-simd-clauses: make 'n' private to avoid firstprivate of uninitialized variables

Co-authored-by: Jakub Jelínek <jakub@redhat.com>

Co-authored-by: Jakub Jelínek <jakub@redhat.com>